-- Add Match-V5 participant metrics to the matches table.
-- Idempotent: safe to run on an existing database more than once.

-- Vision
ALTER TABLE matches ADD COLUMN IF NOT EXISTS vision_score INTEGER DEFAULT 0;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS wards_placed INTEGER DEFAULT 0;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS wards_killed INTEGER DEFAULT 0;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS control_wards_bought INTEGER DEFAULT 0;

-- Damage breakdown
ALTER TABLE matches ADD COLUMN IF NOT EXISTS damage_taken INTEGER DEFAULT 0;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS damage_self_mitigated INTEGER DEFAULT 0;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS damage_to_turrets INTEGER DEFAULT 0;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS damage_to_objectives INTEGER DEFAULT 0;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS total_heal INTEGER DEFAULT 0;

-- Objective participation
ALTER TABLE matches ADD COLUMN IF NOT EXISTS turret_takedowns INTEGER DEFAULT 0;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS inhibitor_takedowns INTEGER DEFAULT 0;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS dragon_kills INTEGER DEFAULT 0;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS baron_kills INTEGER DEFAULT 0;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS objectives_stolen INTEGER DEFAULT 0;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS first_blood BOOLEAN DEFAULT FALSE;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS first_tower BOOLEAN DEFAULT FALSE;

-- Economy and level
ALTER TABLE matches ADD COLUMN IF NOT EXISTS gold_earned INTEGER DEFAULT 0;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS total_cs INTEGER DEFAULT 0;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS champ_level INTEGER DEFAULT 0;

-- Combat highlights
ALTER TABLE matches ADD COLUMN IF NOT EXISTS largest_killing_spree INTEGER DEFAULT 0;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS largest_multi_kill INTEGER DEFAULT 0;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS double_kills INTEGER DEFAULT 0;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS triple_kills INTEGER DEFAULT 0;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS quadra_kills INTEGER DEFAULT 0;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS penta_kills INTEGER DEFAULT 0;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS time_ccing_others INTEGER DEFAULT 0;
